# Generated automatically from Makefile.in by configure.

SHELL=/bin/sh

prefix=/usr/local
pixmaps_dir=/usr/local/lib/X11/pixmaps

INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
RM=rm -f

PIXMAPS=Calculator.xpm \
	Jxlock.xpm \
	MailEmpty.xpm \
	MailFull.xpm \
	Mosaic.xpm \
	N.xpm \
	Pinky.xpm \
	Terminal.xpm \
	Xfm.xpm \
	arrdown2.xpm \
	arrows.xpm \
	arrows2.xpm \
	arrup2.xpm \
	atom.xpm \
	bckgnd1.xpm \
	bckgnd3.xpm \
	bell.xpm \
	bomb.xpm \
	bomb_3d.xpm \
	book_index.xpm \
	book_library.xpm \
	clamp.xpm \
	color_chart.xpm \
	colormap.xpm \
	colours.xpm \
	communicatora1616.xpm \
	communicatora3232.xpm \
	communicatorb1616.xpm \
	communicatorb3232.xpm \
	communicatorc1616.xpm \
	communicatorc3232.xpm \
	communicatord1616.xpm \
	communicatord3232.xpm \
	communicatore1616.xpm \
	communicatore3232.xpm \
	communicatorf1616.xpm \
	communicatorf3232.xpm \
	communicatorg1616.xpm \
	communicatorg3232.xpm \
	communicatorh1616.xpm \
	communicatorh3232.xpm \
	communicatori1616.xpm \
	communicatori3232.xpm \
	communicatorj1616.xpm \
	communicatorj3232.xpm \
	communicatork1616.xpm \
	communicatork3232.xpm \
	communicatorl1616.xpm \
	communicatorl3232.xpm \
	date.xpm \
	datebook.xpm \
	desk.xpm \
	desktop.xpm \
	dialog_box.xpm \
	disk.xpm \
	disk_3D.xpm \
	disk_run.xpm \
	display.xpm \
	documents.xpm \
	dont_panic.xpm \
	doombig.xpm \
	doomface.xpm \
	editres.xpm \
	eps.xpm \
	exit.xpm \
	explorer.xpm \
	find1.xpm \
	flow_chart.xpm \
	folder2.xpm \
	folders.xpm \
	fonts.xpm \
	fruit.xpm \
	fv.xpm \
	fvwm.xpm \
	fvwm2.xpm \
	fvwm3.xpm \
	fvwm95_big.xpm \
	globe.xpm \
	gnu-animal.xpm \
	graphs.xpm \
	gv.xpm \
	help.xpm \
	index.xpm \
	info.xpm \
	jewelbig.xpm \
	keyboard.xpm \
	label1.xpm \
	label2.xpm \
	label3.xpm \
	lemacs.xpm \
	mag_glass.xpm \
	magnify.xpm \
	mail.xpm \
	mail1.xpm \
	mail2.xpm \
	map.xpm \
	math4.xpm \
	netscape_3d.xpm \
	network.xpm \
	new.xpm \
	news2.xpm \
	next.xpm \
	notepad.xpm \
	nscape.xpm \
	onyx1616.xpm \
	onyx3232.xpm \
	owl.xpm \
	page.xpm \
	page2.xpm \
	palette2.xpm \
	pointer.xpm \
	prev.xpm \
	programs.xpm \
	ps.xpm \
	quake.xpm \
	question.xpm \
	rbomb.xpm \
	rcalc.xpm \
	recycler.xpm \
	rterm.xpm \
	run.xpm \
	scilab-color.xpm \
	scilab.xpm \
	settings.xpm \
	shutdown.xpm \
	small.Paint2.xpm \
	small.Shell2.xpm \
	small.exit.xpm \
	small.lock.xpm \
	small.man.next.xpm \
	small.note.next.xpm \
	small.tools2_3d.xpm \
	smallx.xpm \
	snail.xpm \
	snoopy.xpm \
	sysedi.xpm \
	tas.xpm \
	term.xpm \
	textedit.xpm \
	tiff2.xpm \
	toolbox.xpm \
	toolbox_3d.xpm \
	uk.xpm \
	unknown1.xpm \
	wierd_page3.xpm \
	wilber.xpm \
	window.xpm \
	word_processor.xpm \
	world.xpm \
	write.next.xpm \
	wterm.xpm \
	x.xpm \
	x_server.xpm \
	xblast.xpm \
	xboingbig.xpm \
	xcalc.xpm \
	xedit.xpm \
	xedit_w.xpm \
	xemacs-icon.xpm \
	xemacs.xpm \
	xgl.xpm \
	xgrab.xpm \
	xhelp.backward.xpm \
	xhelp.exclaim.xpm \
	xhelp.forward.xpm \
	xhelp.index.xpm \
	xhelp.search.xpm \
	xlab.xpm \
	xlock.xpm \
	xmag.xpm \
	xmail.xpm \
	xman.xpm \
	xmosaic.xpm \
	xmosaic_w.xpm \
	xnomail.xpm \
	xoldmail.xpm \
	xpaint.xpm \
	xpovicon.xpm \
	xscrabble.xpm \
	xterm-axp.xpm \
	xterm-blank.xpm \
	xterm-dec.xpm \
	xterm-sgi.xpm \
	xterm-sol.xpm \
	xterm-sun.xpm \
	xterm.xpm \
	xterm2.xpm \
	xv.color.xpm \
	xv.xpm \
	xview.xpm 


all:

install:
	@echo Installing pixmaps in ${pixmaps_dir}  
	@mkdir -p ${pixmaps_dir}
	@for i in ${PIXMAPS}; do \
	(${INSTALL_DATA} $$i ${pixmaps_dir}) \
	done


uninstall:
	@echo Uninstalling pixmaps
	@for i in ${PIXMAPS}; do \
	(${RM} ${pixmaps_dir}/$$i) \
	done

clean:

distclean:

