# Generated automatically from Makefile.in by configure.

SHELL=/bin/sh

prefix=/usr/local
icon_dir=/usr/local/lib/X11/mini-icons

INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
RM=rm -f

ICONS=	apm-alert.xpm \
	apm-empty.xpm \
	apm-full.xpm \
	apm-half.xpm \
	apm-loading.xpm \
	apm-online.xpm \
	apm-unknown.xpm \
	bckgnd1.xpm \
	bckgnd3.xpm \
	documents.xpm \
	find1.xpm \
	folder.xpm \
	freebsd-menu.xpm \
	fvwm-menu.xpm \
	help.xpm \
	linux-menu.xpm \
	menu.xpm \
	mini-arch.xpm \
	mini-asmail.xpm \
	mini-audiovol.xpm \
	mini-ball.xpm \
	mini-bball.xpm \
	mini-bomb.xpm \
	mini-book1.xpm \
	mini-book2.xpm \
	mini-books.xpm \
	mini-briefcase.xpm \
	mini-bug1.xpm \
	mini-bug2.xpm \
	mini-bx2.xpm \
	mini-calc.xpm \
	mini-camera.xpm \
	mini-cat.xpm \
	mini-cave.xpm \
	mini-cd.xpm \
	mini-cdlabel.xpm \
	mini-chinese.xpm \
	mini-clipboard.xpm \
	mini-clock.xpm \
	mini-colors.xpm \
	mini-connect.xpm \
	mini-crosbone.xpm \
	mini-cross.xpm \
	mini-desktop.xpm \
	mini-dfolder.xpm \
	mini-diff.xpm \
	mini-diskette.xpm \
	mini-display.xpm \
	mini-doc.xpm \
	mini-doc1.xpm \
	mini-dog.xpm \
	mini-dos.xpm \
	mini-edit.xpm \
	mini-espada.xpm \
	mini-exclam.xpm \
	mini-exp.xpm \
	mini-eye.xpm \
	mini-eyes.xpm \
	mini-fax.xpm \
	mini-fdisk.xpm \
	mini-filemgr.xpm \
	mini-firefox.xpm \
	mini-folder.xpm \
	mini-font.xpm \
	mini-fractal.xpm \
	mini-frame.xpm \
	mini-ftp.xpm \
	mini-gball.xpm \
	mini-go.xpm \
	mini-gopher.xpm \
	mini-graph.xpm \
	mini-gv.xpm \
	mini-hammer.xpm \
	mini-happy.xpm \
	mini-hdisk.xpm \
	mini-heart.xpm \
	mini-hex.xpm \
	mini-hextris.xpm \
	mini-iceweasel.xpm \
	mini-iconify.xpm \
	mini-icons.xpm \
	mini-keyboard.xpm \
	mini-lightbolt-full.xpm \
	mini-lock.xpm \
	mini-lower.xpm \
	mini-mail.xpm \
	mini-manual.xpm \
	mini-max1.xpm \
	mini-maxtall.xpm \
	mini-maxwide.xpm \
	mini-maze.xpm \
	mini-modules.xpm \
	mini-monitor.xpm \
	mini-mouse.xpm \
	mini-move.xpm \
	mini-move1.xpm \
	mini-mwm.xpm \
	mini-newmail.xpm \
	mini-news.xpm \
	mini-nscape.xpm \
	mini-ofolder.xpm \
	mini-olwm.xpm \
	mini-pager.xpm \
	mini-paint.xpm \
	mini-palette.xpm \
	mini-pdf.xpm \
	mini-pencil.xpm \
	mini-penguin.xpm \
	mini-perf.xpm \
	mini-question.xpm \
	mini-raise.xpm \
	mini-ray.xpm \
	mini-rball.xpm \
	mini-redhat.xpm \
	mini-resize.xpm \
	mini-roach.xpm \
	mini-run.xpm \
	mini-seamonkey.xpm \
	mini-sh.xpm \
	mini-sh1.xpm \
	mini-slon.xpm \
	mini-sound.xpm \
	mini-speaker-off.xpm \
	mini-speaker.xpm \
	mini-start.xpm \
	mini-stop.xpm \
	mini-telnet.xpm \
	mini-term.xpm \
	mini-tetris.xpm \
	mini-trebol.xpm \
	mini-turn.xpm \
	mini-twm.xpm \
	mini-unreadmail.xpm \
	mini-wilber.xpm \
	mini-window.xpm \
	mini-windows.xpm \
	mini-x.xpm \
	mini-x2.xpm \
	mini-xfig.xpm \
	mini-xjewel.xpm \
	mini-xkeycaps.xpm \
	mini-xlander.xpm \
	mini-xmahjongg.xpm \
	mini-xsnow.xpm \
	mini-xv.xpm \
	mini-zoom.xpm \
	mini.FileManager.xpm \
	mini.audiovol.xpm \
	mini.blah.xpm \
	mini.checkmark.xpm \
	mini.cut.xpm \
	mini.destroy.xpm \
	mini.excl.xpm \
	mini.exit.xpm \
	mini.fvwm.xpm \
	mini.install_3d.xpm \
	mini.key_3d.xpm \
	mini.letter.xpm \
	mini.lower.xpm \
	mini.move.xpm \
	mini.netscape.xpm \
	mini.rainbow.xpm \
	mini.raise.xpm \
	mini.resize.xpm \
	mini.stick.xpm \
	mini.stick2.xpm \
	mini.text.xpm \
	mini.win95.xpm \
	mini.window3d.xpm \
	mini.xarchie.xpm \
	mini.xboing.xpm \
	mini.xlock.xpm \
	mini.xpm \
	mini.xterm.xpm \
	mini.zircon.xpm \
	onyx1616.xpm \
	onyx3232.xpm \
	programs.xpm \
	run.xpm \
	run1616.xpm \
	settings.xpm \
	shutdown.xpm \
	solaris95.xpm \
	sun-menu.xpm \
	utilities-menu.xpm 


all:

install:
	@echo Installing mini-icons in ${icon_dir}  
	@mkdir -p ${icon_dir}
	@for i in ${ICONS}; do \
	(${INSTALL_DATA} $$i ${icon_dir}) \
	done


uninstall:
	@echo Uninstalling mini-icons  
	@for i in ${ICONS}; do \
	(${RM} ${icon_dir}/$$i) \
	done


clean:

distclean:
