/**************************************************************************

    This file is part of a xclass desktop manager.
    Copyright (C) 1996-2000 David Barth, Hector Peraza.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

**************************************************************************/

#ifndef __OXDESKTOPROOT_H
#define __OXDESKTOPROOT_H

#include <X11/Xlib.h>

#include <xclass/OXRootWindow.h>
#include <xclass/OMessage.h>

class OXGC;
class OXDesktopMain;


//----------------------------------------------------------------------
// Messages generated by OXDesktopRoot

#define MSG_DESKTOPROOT      (MSG_USERMSG+1246)


class ODesktopRootMessage : public OMessage {
public:
  ODesktopRootMessage(int typ, int act, int b, int xr, int yr) :
    OMessage(typ, act) { button = b; x_root = xr; y_root = yr; }
      
public:
  int button, x_root, y_root;
};
      

//----------------------------------------------------------------------
// Root window proxy object. Needed in order to process root window
// mouse events.

class OXDesktopRoot : public OXRootWindow {
public:
  OXDesktopRoot(OXClient *c, OXDesktopMain *main, int *retc);
  virtual ~OXDesktopRoot();
  
  virtual int HandleEvent(XEvent *event);
  virtual int HandleMaskEvent(XEvent *event);

  virtual int HandleButton(XButtonEvent *event);
  virtual int HandleMotion(XMotionEvent *event);

protected:
  static int ErrorHandler(Display *dpy, XErrorEvent *event);
  static int _errorCode;

protected:
  void DrawDragOutline();

  OXGC *_lineGC;
  int _x0, _y0, _x1, _y1, _dragSelecting;
  OXDesktopMain *_main;
};


#endif  // __OXDESKTOPROOT_H
