#!/bin/sh

xclass_libs=""
xclass_cflags=""

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

lib_dir=${prefix}/lib
include_dir=/usr/local/include

usage()
{
	cat <<EOF
Usage: xc-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
	xclass
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_xclass=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 0.9.2
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    xclass)
      lib_xclass=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi

if test "$echo_cflags" = "yes"; then
      if test "$include_dir" != "/usr/include" ; then
        includes=$include_dir
        for i in $xclass_cflags ; do
          if test $i = -I$include_dir ; then
            includes=""
          fi
        done
      fi
      if test "$includes" != "" ; then
        includes=-I$includes
      fi
      echo $includes  $xclass_cflags
fi

if test "$echo_libs" = "yes"; then
      my_xclass_libs=
      libdirs=-L$lib_dir
      for i in $xclass_libs ; do
        if test $i != -L$lib_dir ; then
          if test -z "$my_xclass_libs" ; then
            my_xclass_libs="$i"
          else
            my_xclass_libs="$my_xclass_libs $i"
          fi
        fi
      done

      echo $libdirs $my_xclass_libs -lxclass  -lGLU -lGL -lXpm -lXext -lX11
fi      

